image: oven/bun:latest

stages:
  - install
  - lint
#  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - bun install
  artifacts:
    paths:
      - node_modules/

lint: # This will generate alot of errors
  stage: lint
  script:
    - bun run lint
  allow_failure: true  # This allows the pipeline to continue even if linting fails

#test: # Will add later
#  stage: test
#  script:
#    - bun test

build:
  stage: build
  script:
    - bun run build
  artifacts:
    paths:
      - dist/
